package com.yunfei.greendao.demo.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import db.bean.School;
import db.bean.Student;
import db.bean.Clazz;
import db.bean.IDCard;
import com.yunfei.greendao.demo.bean.Chapter;
import com.yunfei.greendao.demo.bean.GoodsCourse;
import com.yunfei.greendao.demo.bean.Lecture;

import com.yunfei.greendao.demo.db.greendao.SchoolDao;
import com.yunfei.greendao.demo.db.greendao.StudentDao;
import com.yunfei.greendao.demo.db.greendao.ClazzDao;
import com.yunfei.greendao.demo.db.greendao.IDCardDao;
import com.yunfei.greendao.demo.db.greendao.ChapterDao;
import com.yunfei.greendao.demo.db.greendao.GoodsCourseDao;
import com.yunfei.greendao.demo.db.greendao.LectureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig schoolDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig clazzDaoConfig;
    private final DaoConfig iDCardDaoConfig;
    private final DaoConfig chapterDaoConfig;
    private final DaoConfig goodsCourseDaoConfig;
    private final DaoConfig lectureDaoConfig;

    private final SchoolDao schoolDao;
    private final StudentDao studentDao;
    private final ClazzDao clazzDao;
    private final IDCardDao iDCardDao;
    private final ChapterDao chapterDao;
    private final GoodsCourseDao goodsCourseDao;
    private final LectureDao lectureDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        schoolDaoConfig = daoConfigMap.get(SchoolDao.class).clone();
        schoolDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        clazzDaoConfig = daoConfigMap.get(ClazzDao.class).clone();
        clazzDaoConfig.initIdentityScope(type);

        iDCardDaoConfig = daoConfigMap.get(IDCardDao.class).clone();
        iDCardDaoConfig.initIdentityScope(type);

        chapterDaoConfig = daoConfigMap.get(ChapterDao.class).clone();
        chapterDaoConfig.initIdentityScope(type);

        goodsCourseDaoConfig = daoConfigMap.get(GoodsCourseDao.class).clone();
        goodsCourseDaoConfig.initIdentityScope(type);

        lectureDaoConfig = daoConfigMap.get(LectureDao.class).clone();
        lectureDaoConfig.initIdentityScope(type);

        schoolDao = new SchoolDao(schoolDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        clazzDao = new ClazzDao(clazzDaoConfig, this);
        iDCardDao = new IDCardDao(iDCardDaoConfig, this);
        chapterDao = new ChapterDao(chapterDaoConfig, this);
        goodsCourseDao = new GoodsCourseDao(goodsCourseDaoConfig, this);
        lectureDao = new LectureDao(lectureDaoConfig, this);

        registerDao(School.class, schoolDao);
        registerDao(Student.class, studentDao);
        registerDao(Clazz.class, clazzDao);
        registerDao(IDCard.class, iDCardDao);
        registerDao(Chapter.class, chapterDao);
        registerDao(GoodsCourse.class, goodsCourseDao);
        registerDao(Lecture.class, lectureDao);
    }
    
    public void clear() {
        schoolDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        clazzDaoConfig.clearIdentityScope();
        iDCardDaoConfig.clearIdentityScope();
        chapterDaoConfig.clearIdentityScope();
        goodsCourseDaoConfig.clearIdentityScope();
        lectureDaoConfig.clearIdentityScope();
    }

    public SchoolDao getSchoolDao() {
        return schoolDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public ClazzDao getClazzDao() {
        return clazzDao;
    }

    public IDCardDao getIDCardDao() {
        return iDCardDao;
    }

    public ChapterDao getChapterDao() {
        return chapterDao;
    }

    public GoodsCourseDao getGoodsCourseDao() {
        return goodsCourseDao;
    }

    public LectureDao getLectureDao() {
        return lectureDao;
    }

}
